### ISSUE TITLE
MDC-103 AccentColorOverride

### ISSUE THREAD

**Issue by dav-vendator** [material-components/material-components-flutter-codelabs#132]
Under step number 5; Changing Typography; The Section where AccentColorOverride class is used to override the accentColor doesn't changes the color of textfields (username, password) when copyWIth(accentColor : kShrineBrown900) but it works when copyWith(primaryColor : kShrineBrown900). 
my flutter version is 0.8.2. I am using Android Device for testing.

**Comment by willlarche** [comment]
This should be corrected now both in document and sample code. Thank you!

**Comment by FlashJonas** [comment]
This issue persists. https://codelabs.developers.google.com/codelabs/mdc-103-flutter/#4

The code in the example box and the repo doesn't match. But the image in the example matches the result from the repo code. 

Diff is: "brightness: Brightness.dark", add this to the example code and it looks like the picture.
